name: application
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.1 <4.0.0'  # Ensure proper SDK constraints

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0  # Latest version of carousel_slider
  cupertino_icons: ^1.0.8  # Latest version of cupertino_icons
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  google_sign_in: ^6.3.0
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  google_fonts: ^6.1.0
  cloud_firestore: ^4.14.0
  razorpay_flutter: ^1.3.6
  fluttertoast: ^8.2.4
  pdf: ^3.10.8
  path_provider: ^2.1.2
  open_file: ^3.3.2
  flutter_rating_bar: ^4.0.1
  flutter_pdfview: ^1.3.2
  phone_email_auth: ^0.0.6
  crypto: ^3.0.3
  firebase_storage: ^11.6.0
  image_picker: ^1.0.5
  permission_handler: ^11.3.0
  device_info_plus: ^9.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Latest version of flutter_lints
  flutter_launcher_icons: ^0.14.3  # Added flutter_launcher_icons

flutter:
  uses-material-design: true
  generate: true

  assets:
    - images/

flutter_icons:
  android: true
  ios: true
  image_path: "images/applogooo.png"  # Ensure this path is correct

flutter_intl:
  enabled: true
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
