// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUmCGDKw1At8OCzk_VluCKFK3a9uEYDus',
    appId: '1:581932893864:web:1c3986b5d8598d44ff649d',
    messagingSenderId: '581932893864',
    projectId: 'movies-bf489',
    authDomain: 'movies-bf489.firebaseapp.com',
    storageBucket: 'movies-bf489.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBef10LCit3xsffs7pHEdik9yYs6nNUdA',
    appId: '1:581932893864:android:2c0c7f453deef9faff649d',
    messagingSenderId: '581932893864',
    projectId: 'movies-bf489',
    storageBucket: 'movies-bf489.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtADCa6fkU8WvTRTgQ4MNm4sL5mfkWk9Q',
    appId: '1:581932893864:ios:78a8e5fefb396e43ff649d',
    messagingSenderId: '581932893864',
    projectId: 'movies-bf489',
    storageBucket: 'movies-bf489.firebasestorage.app',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtADCa6fkU8WvTRTgQ4MNm4sL5mfkWk9Q',
    appId: '1:581932893864:ios:78a8e5fefb396e43ff649d',
    messagingSenderId: '581932893864',
    projectId: 'movies-bf489',
    storageBucket: 'movies-bf489.firebasestorage.app',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUmCGDKw1At8OCzk_VluCKFK3a9uEYDus',
    appId: '1:581932893864:web:e2d87ab0df185d21ff649d',
    messagingSenderId: '581932893864',
    projectId: 'movies-bf489',
    authDomain: 'movies-bf489.firebaseapp.com',
    storageBucket: 'movies-bf489.firebasestorage.app',
  );
}
